name=Filters
version=0.9.4
author=Martin Budden
maintainer=Martin Budden
sentence=Filters library
paragraph=including IIR, FIR, moving average, and low-pass filters
category=Device Control
url=https://github.com/martinbudden/Library-Filters.git
architectures=*
includes=filters.h,FilterTemplates.h,circular_buffer.h,rolling_buffer.h
